package com.huodaizi.backend.repository.dashboard;

import java.util.List;

public record A01DashboardAggregate(
    int inquiryTotal,
    int inquiryOpenCount,
    int inquiryQuotingCount,
    int inquiryDealDoneCount,
    int inquiryClosedCount,
    int merchantLeadTotal,
    int merchantLeadNewCount,
    int merchantLeadQuotedCount,
    int merchantLeadWonCount,
    int merchantLeadLostCount,
    int pickupOrderTotal,
    int pickupInTransitCount,
    int pickupSignedCount,
    int pickupCompletedCount,
    int pickupCancelledCount,
    int reconcileOrderTotal,
    int reconcilePartialPaidCount,
    int reconcilePaidCount,
    int reconcileDisputedCount,
    int subscriptionTotal,
    int subscriptionActiveCount,
    int subscriptionExpiringSoonCount,
    int subscriptionExpiredCount,
    int billingOutstandingCount,
    java.math.BigDecimal billingOutstandingAmountYuan,
    int adLeadTotal,
    int adLeadSubmittedCount,
    int adLeadAssignedCount,
    int adLeadContactedCount,
    int adLeadProposalSentCount,
    int adLeadConvertedCount,
    java.math.BigDecimal reconcilePaidAmountYuan,
    java.math.BigDecimal reconcileReceivableAmountYuan,
    java.math.BigDecimal reconcileOutstandingAmountYuan,
    java.math.BigDecimal leadAmountYuan,
    java.math.BigDecimal subscriptionAmountYuan,
    java.math.BigDecimal adLeadBudgetAmountYuan,
    String pickupOnTimeRate,
    String averageResponseMinutes,
    List<DailyPoint> dailyPoints) {
  public record DailyPoint(
      String date,
      int inquiryCount,
      int quoteCount,
      int dealCount,
      int pickupCount,
      int paidCount,
      int memberOpenCount,
      int adLeadCount,
      String paidAmountYuan) {}
}
