package com.huodaizi.backend.dto.auth;

import java.util.List;

public record N06OrderDetailResponse(
    String orderId,
    String orderNo,
    String inquiryId,
    String inquiryNo,
    String quoteId,
    String sessionId,
    String orderStatus,
    String orderStatusText,
    String buyerCompany,
    String buyerContact,
    String buyerPhoneMasked,
    String supplierName,
    String goodsName,
    String specText,
    String quantityTon,
    String unitPrice,
    String totalAmount,
    String taxIncluded,
    String paymentTerm,
    String expectedDeliveryDate,
    String latestRemark,
    String pickupStatus,
    String pickupStatusText,
    String pickupNo,
    String pickupAddress,
    String reconcileStatus,
    String reconcileStatusText,
    String reconcileNo,
    String receivableAmount,
    String paidAmount,
    String outstandingAmount,
    String createdAt,
    String updatedAt,
    List<N06OrderTimelineNodeDTO> timeline,
    List<N06OrderActionDTO> actions) {}
