package com.huodaizi.backend.dto.auth;

public record N12InvoiceApplicationDetailResponse(
    String invoiceApplyId,
    String orderId,
    String orderNo,
    String inquiryNo,
    String buyerCompany,
    String supplierName,
    String amountWithTax,
    String invoiceType,
    String invoiceTypeText,
    String invoiceStatus,
    String invoiceStatusText,
    String titleId,
    String titleName,
    String taxNo,
    String registerAddress,
    String registerPhone,
    String bankName,
    String bankAccountNo,
    String receiverName,
    String receiverPhone,
    String receiverAddress,
    String email,
    String courierNo,
    String expressCompany,
    String latestRemark,
    String createdAt,
    String updatedAt) {}
