package com.huodaizi.backend.dto.admn11;

import java.util.List;

public record Admn11PaymentRefundDetailResponse(
    String refundId,
    String refundNo,
    String cashierOrderId,
    String orderId,
    String orderNo,
    String inquiryNo,
    String buyerCompany,
    String supplierName,
    String goodsName,
    String refundType,
    String refundTypeText,
    String refundReasonCode,
    String refundReasonText,
    String refundStatus,
    String refundStatusText,
    String payChannel,
    String payChannelText,
    String payableAmount,
    String paidAmount,
    String refundAmount,
    String approvedAmount,
    String refundedAmount,
    String remainingAmount,
    String applicant,
    String reviewer,
    String financeOperator,
    String latestRemark,
    String requestedAt,
    String reviewedAt,
    String createdAt,
    String updatedAt,
    String refundedAt,
    String rejectReason,
    List<Admn11PaymentRefundProgressNodeDTO> progressNodes,
    List<String> availableActions) {}
